<div class="row">
  <div class="col-md-6 img-title">
    <img src="<?php echo $constants['static_url']; ?>competition/assets/img/title.png" alt="" class="mx-auto d-block">
  </div>
  <div class="col-md-6 img-tree">
    <img src="<?php echo $constants['static_url']; ?>competition/assets/img/tree.png" alt="" class="mx-auto d-block">
  </div>
</div>
<div class="row">
  <div class="col-md-6">
  </div>
  <div class="col-md-6 text-md-center links">
    <a href="<?php echo $constants['base_url']; ?>competition/#/info" class="link">BASES</a>
    <a href="<?php echo $constants['base_url']; ?>competition/#/sign_in" class="link">INSCRIPCIÓN</a>
  </div>
</div>
